### PR TITLE
fix pluggable auth CSRF warnings on zope root

### PR DESCRIPTION
**Pull request by vangheem**
Just let plone.protect do it's job also on zope root

### CODE REVIEW

**Comment by vangheem** [comment]
tests running here: http://jenkins.plone.org/job/pull-request-5.0/134/

**Comment by vangheem** [comment]
next try: http://jenkins.plone.org/job/pull-request-5.0/135/

last one had a jenkins error.

**Comment by vangheem** [comment]
http://jenkins.plone.org/job/pull-request-5.0/136/

**Comment by tisto** [comment]
Released: https://pypi.python.org/pypi/plone.protect cc @esteele

**Pull request merged**
