### PR TITLE
do not depend here on plone.portlets

### PR DESCRIPTION
**Pull request by jensens**
prepare for a world without portlets.

### CODE REVIEW

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
@jensens It looks like you created a 4.x branch *after* merging this PR, and let coredev 5.2 use it.  We don't want this code on Plone 5.2 I think.  Is it okay if I revert the change on the 4.x branch?  Or you can do it.

**Comment by jensens** [comment]
Ops. I'll branch away from prior my commit, ok?

**Comment by mauritsvanrees** [comment]
Yes, that should be fine too.

**Comment by mauritsvanrees** [comment]
Well, I decided to revert the commit in 68ba6848cf06010fe9fc36147084ddaac185383f.  Less nice git history, but better for people who have meanwhile gotten the 4.x branch.

**Pull request merged**
