### PR TITLE
Fix for content-type header check and environment variable check.

### PR DESCRIPTION
**Pull request by mauritsvanrees**

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
http://jenkins.plone.org/job/pull-request-5.0/447/

**Comment by davisagli** [comment]
We also need a way to disable the X-Frame-Options header so sites can opt in to being iframeable.

**Comment by vangheem** [comment]
Should we just advise to remove the X-Frame-Options header at the proxy server instead?

**Comment by mauritsvanrees** [comment]
We can easily do this in plone.protect:

```
        if X_FRAME_OPTIONS:
            self.request.response.setHeader('X-Frame-Options', X_FRAME_OPTIONS)
```

**Comment by vangheem** [comment]
sure, that's fine too. Just saying it might be easier for people to add a proxy config than change a process start script.

**Comment by mauritsvanrees** [comment]
Pull request updated.
New Jenkins: http://jenkins.plone.org/job/pull-request-5.0/448/

**Comment by mauritsvanrees** [comment]
For me it is easier to change to process startup script than to add a proxy config. ;-)

**Comment by mauritsvanrees** [comment]
The first Jenkins job has passed, but let's wait for the new one to finish.

**Comment by mauritsvanrees** [comment]
Second Jenkins passes too. All green.

**Pull request merged**
