### PR TITLE
Clean up the monkey patch for CMFFormController RedirectTo.

### PR DESCRIPTION
**Pull request by fredvd**

### CODE REVIEW

**Comment by jensens** [comment]
see plone/Products.CMFFormController#3

**Comment by jensens** [comment]
Is this still an issue?

**Comment by gforcada** [comment]
@mauritsvanrees you did merge this method that plone.protect patches into CMFFormController, is this monkeypatch here still needed?

**Comment by mauritsvanrees** [comment]
This was already handled in pull request #53, included in plone.protect 3.0.20. So this can be closed.

**Pull request closed without merging**
