### PR TITLE
testing: explicitly set response content type header to html

### PR DESCRIPTION
**Pull request by perrinjerome**

### CODE REVIEW

**Comment by perrinjerome** [comment]
BTW, there's something strange in  https://plone.org/foundation/about/materials/foundation-resolutions/patch-policy-052011

image

**Comment by perrinjerome** [comment]
This is an early follow up for https://github.com/zopefoundation/Zope/pull/1075 

This falls in 

> Changes required by changes in other modules that introduce no new logic.

category, so I guess contributor agreement will not be needed

**Review by mauritsvanrees — APPROVED** [review]
LGTM. Let me start the tests on Jenkins by adding this comment:

@jenkins-plone-org please run jobs

I have fixed the text in the agreement page, it indeed looked ugly.

As Plone Release Manager I agree that this is a fix that does not require having signed the Plone contributor agreement. I still recommend signing it, if you agree with it and foresee more fixes in the near future. But for this one it is fine.

I approve this PR, but the tests should be green first, let's wait for that.

**Comment by mauritsvanrees** [comment]
Why did this not work? Trying again:

@jenkins-plone-org please run jobs

Might be because [mr.roboto](https://github.com/plone/mr.roboto) cannot handle the fork of the repo.

**Comment by mauritsvanrees** [comment]
All tests pass, except two unrelated robot tests on 5.2. I merge. Thanks!

**Comment by perrinjerome** [comment]
Thank you very much @mauritsvanrees for reviewing the patches, trying them on CI and also accepting that this was OK as an exception to the contributor agreement. I probably don't have a problem with this agreement, but this would need to be validated by my employer. This is probably OK as well, but I was lazy of going through the paperwork. Thanks again.

**Pull request merged**
